#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FallDetector.Resource", IsApplication=true)]

namespace FallDetector
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomTextButtonColor = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlueMinus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Button_Selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Custom_Background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CustomButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int FallingIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Minus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Plus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Warning = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int accelerometerButton = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int button1 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int fallCountTextView = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int fallTextView = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int inclinationButton = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int orientationButton = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int plotmodel = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int plotview = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout1 = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlertLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int plot = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int Mono_Android_Theme_Splash = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int styleButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int styleText = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
